name: e2e-terratest

on:
  workflow_dispatch:

jobs:
  test:
    name: Run E2E Terratest
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Setup Dependencies
        working-directory: test/src
        run: go get -v -t -d && go mod tidy -compat=1.17

      - name: Run Go E2E Tests
        working-directory: test/src
        run: go test -v -timeout 60m -tags=e2e
