name: e2e-all-examples-parallel

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: E2E Example
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tf_working_dir:
          [
            examples/analytics/emr-on-eks,
            examples/analytics/spark-k8s-operator,
            examples/gitops/argocd,
            examples/aws-efs-csi-driver,
            examples/crossplane,
            examples/eks-cluster-with-new-vpc,
            examples/fully-private-eks-cluster,
            examples/game-tech/agones-game-controller,
            examples/ingress-controllers/nginx,
            examples/karpenter,
            examples/multi-tenancy-with-teams,
            examples/node-groups/managed-node-groups,
            examples/node-groups/self-managed-node-groups,
            examples/node-groups/windows-node-groups,
            examples/node-groups/fargate-profiles
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Terraform Job
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check -recursive -list -no-color
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure
        working-directory: ${{ matrix.tf_working_dir }}
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform validate -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform plan -no-color
        continue-on-error: false
